# Generated by Django 4.0.6 on 2023-03-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='valuation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.AddField(
            model_name='employee',
            name='budget',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
