# Generated by Django 4.0.6 on 2023-03-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, max_length=80, null=True)),
                ('budget', models.IntegerField()),
                ('valuation', models.IntegerField()),
            ],
        ),
    ]
